vue-vine/vue-vine

packages/vite-plugin/package.json
use `cross-env` to support windows environment variables.
=> feat: support windows

packages/vue-vine/package.json
=> chore: use rimraf

packages/docs/design/spec.md
=> docs: change `vite.ts` to `vine.ts`

packages/compiler/src/transform.ts, packages/compiler/test/__snapshots__/css-vars.spec.ts.snap, packages/compiler/test/__snapshots__/transform.spec.ts.snap, packages/compiler/test/css-vars.spec.ts, packages/compiler/test/transform.spec.ts
=> fix: fix await compile error

packages/compiler/src/analyze.ts, packages/compiler/test/__snapshots__/transform.spec.ts.snap, packages/compiler/test/template.spec.ts, packages/compiler/test/transform.spec.ts
=> fix: didn't recongnize props binding

packages/compiler/src/analyze.ts, packages/compiler/src/ast-grep/rules-for-script.ts, packages/compiler/src/style/order.ts, packages/compiler/src/transform.ts, packages/compiler/src/types.ts, packages/compiler/test/__snapshots__/transform.spec.ts.snap, packages/compiler/test/css-vars.spec.ts, packages/compiler/test/transform.spec.ts
=> feat: added a marco function `vineCE` to mark web component

packages/vite-plugin/index.ts
=> fix: sourcemap support

packages/docs/src/specification/basics.md
=> docs: fix grammar mistakes

packages/docs/src/introduction/quick-start.md, packages/docs/src/zh/introduction/quick-start.md
=> Incoherent type reference

packages/docs/src/.vitepress/theme/components/recommend.vue, packages/docs/uno.config.ts
Add a gradient background when hovering
Preview:
https://github.com/vue-vine/vue-vine/assets/49969959/2f0ab014-15f8-4563-acad-0d0e1b3703c1
=> docs(style): prettify recommendations

packages/compiler/src/transform.ts, packages/compiler/tests/__snapshots__/transform.spec.ts.snap, packages/compiler/tests/transform.spec.ts, packages/vite-plugin/src/hot-update.ts
=> fix: fixed the problem of hot update error when VCF does not contain style definition

packages/compiler/src/analyze.ts, packages/compiler/tests/__snapshots__/transform.spec.ts.snap, packages/compiler/tests/analyze.spec.ts, packages/playground/src/pages/home.vine.ts, scripts/run-test.js
=> fix(compiler): vineEmits should set in setupBindings

packages/eslint-parser/package.json, packages/eslint-parser/tsup.config.ts, pnpm-lock.yaml
=> chore(eslint-parser): remove external for bundle config

packages/compiler/src/babel-helpers/ast.ts, packages/compiler/tests/analyze.spec.ts, packages/playground/src/pages/home.vine.ts
=> fix(compiler): parsing export default function as component

README-CN.md
fix English colons in README-CN
=> docs: update README-CN

README-CN.md, packages/compiler/src/analyze.ts, packages/create-vue-vine/src/commands/create.ts, packages/create-vue-vine/src/create.ts
fix function name and annotations
=> chore(typo): fix function name and annotations

packages/compiler/src/analyze.ts, packages/compiler/src/transform.ts, packages/compiler/src/types.ts, packages/compiler/tests/__snapshots__/transform.spec.ts.snap, packages/compiler/tests/transform.spec.ts
=> fix(compiler): support export default component function

packages/vscode-ext/language/vine-vue-template-configuration.json, packages/vscode-ext/package.json, packages/vscode-ext/syntaxes/vine-inject.json, packages/vscode-ext/syntaxes/vine-vue-template.json, packages/vscode-ext/syntaxes/vue-directives.json, packages/vscode-ext/syntaxes/vue-interpolations.json
=> fix(vscode-ext): code action hotkey support by language configuration

packages/compiler/src/transform.ts, packages/compiler/tests/__snapshots__/transform.spec.ts.snap, packages/compiler/tests/transform.spec.ts, packages/vscode-ext/CHANGELOG.md, packages/vscode-ext/package.json
=> fix(compiler): wrap async context for await expression

packages/docs/package.json, packages/docs/src/.vitepress/theme/style.css, packages/docs/src/index.md, packages/docs/src/zh/index.md, packages/docs/uno.config.ts, pnpm-lock.yaml
=> docs: prettify home features

packages/docs/src/.vitepress/theme/style.css
=> docs: fix container max-width

CONTRIBUTING-zhCN.md, CONTRIBUTING.md, README-CN.md, README.md
Hello, I drafted a contribution guide, please review it, and once it was finalized, I continued translating it. ( Add CONTRIBUTING-CN.md)
=> docs: add contributing doc

packages/compiler/src/index.ts, packages/compiler/src/types.ts, packages/vite-plugin/package.json, packages/vite-plugin/src/hot-update.ts, packages/vite-plugin/src/index.ts, pnpm-lock.yaml
use transformPluginContext.error to raise errors on root scope.
closes #137
=> refactor(vite): simplify error raising

packages/compiler/package.json, packages/compiler/tsconfig.json, packages/eslint-parser/package.json, packages/playground/package.json, packages/vue-vine/package.json
=> fix(compiler): exports spec for running on Node & ESM

packages/compiler/src/analyze.ts, packages/compiler/src/constants.ts, packages/compiler/src/style/create-import-statement.ts, packages/compiler/src/style/order.ts, packages/compiler/src/types.ts, packages/compiler/tests/__snapshots__/transform.spec.ts.snap, packages/compiler/tests/analyze.spec.ts, packages/compiler/tests/transform.spec.ts, packages/compiler/tests/validate.spec.ts, packages/language-service/src/index.ts, packages/playground/src/pages/home.vine.ts, packages/vite-plugin/src/index.ts, packages/vite-plugin/src/parse-query.ts, packages/vscode-ext/syntaxes/vine-inject.json
=> feat(compiler): support multiple vineStyle

packages/vite-plugin/src/hot-update.ts, packages/vite-plugin/src/utils/index.ts
=> fix(hot-update.ts): 修复热更新vine组件时样式不会更新的问题

packages/compiler/src/analyze.ts, packages/compiler/src/template/compose.ts, packages/compiler/src/transform.ts, packages/compiler/src/types.ts, packages/language-service/src/injectTypes.ts, packages/nuxt-module/package.json, packages/playground/src/auto-imports.d.ts, packages/playground/src/pages/home.vine.ts, packages/playground/tsconfig.json, packages/playground/vite.config.ts, tsconfig.json
=> fix(compiler): compatible with unplugin-auto-import

scripts/post-install.js, scripts/pre-commit.js, scripts/utils/index.js
Original:
This made me run pnpm install on windows...
I even doubt it will ever end.
After:
I have tried many times, and it is still very fast.
=> fix(root): fix the blocking of postinstall on windows

package.json, packages/docs/src/.vitepress/config.ts, packages/docs/src/vine-vibe/usage.md, packages/docs/src/vine-vibe/why.md, packages/docs/src/zh/vine-vibe/usage.md, packages/docs/src/zh/vine-vibe/why.md, packages/vscode-ext/package.json, packages/vue-vine/package.json, packages/vue-vine/src/defineVibe.ts, packages/vue-vine/src/index.ts, packages/vue-vine/tests/define-vibe.spec.ts, packages/vue-vine/vitest.config.mts, pnpm-lock.yaml, vitest.workspace.ts
Vibe is a state management solution for Vue Vine.
Before Vine, you may have known several state management solutions for Vue, such as Pinia, Composable functions, Provide/Inject, etc.
This article from `@alexanderOpalic` [Solving Prop Drilling in Vue: Modern State Management Strategies](https://alexop.dev/posts/solving-prop-drilling-in-vue) compares the pros and cons of these solutions in detail, highly recommended to read.
In Vine, since we have the ability to manage multiple components in a single file, we hope to have a solution that combines the advantages of these solutions to manage states across multiple related components, and also make the editing experience simpler and more convenient, without always having to add and switch files.
=> feat: add Vibe mechanism provided from `vue-vine`

packages/compiler/src/analyze.ts, packages/compiler/src/constants.ts, packages/compiler/src/transform.ts, packages/compiler/src/types.ts, packages/compiler/src/validate.ts, packages/compiler/tests/__snapshots__/transform.spec.ts.snap, packages/compiler/tests/transform.spec.ts, packages/compiler/tests/validate.spec.ts, packages/language-service/src/injectTypes.ts, packages/playground/src/pages/about.vine.ts, types/shims.d.ts
=> feat(compiler): support props destructure as Vue 3.5

.github/workflows/ci.yml, .github/workflows/pkg-pr-new.yml, packages/compiler/src/analyze.ts, packages/compiler/src/ts-morph/resolve-props-type.ts, packages/language-server/src/index.ts, packages/language-service/src/injectTypes.ts, packages/language-service/typescript-plugin/index.ts, packages/playground/src/pages/test-ts-morph.vine.ts, packages/tsc/src/index.ts, pnpm-lock.yaml, pnpm-workspace.yaml
See more details: https://github.com/vuejs/language-tools/releases/tag/v2.2.2
=> enhance: bump vue-language-core to v2.2.2

.github/workflows/ci.yml, package.json, packages/nuxt-module/package.json
- Pass CI checks
- Upgrade dependencies
=> chore: fix project engineering issues.

packages/compiler/src/ts-morph/resolve-props-type.ts, packages/docs/src/introduction/ecosystem.md, packages/docs/src/zh/introduction/ecosystem.md, packages/playground/src/components/fixtures.vine.ts, packages/playground/src/shims.d.ts, packages/playground/tsconfig.json
Thanks to @Soya-xy prompting these issues:
- Fix undefined handling in HMR when ts-morph resolving
- Add docs to mention about compatible solution with UnoCSS attribute mode
=> fix(compiler): undefined handling in HMR for ts-morph

packages/eslint-parser/src/script/scope-analyzer.ts, packages/eslint-parser/src/template/utils/index.ts, packages/eslint-parser/tests/parse.test.ts, packages/playground/src/pages/home.vine.ts
Thanks to @Soya-xy mentioning about this feature.
=> feat(eslint): support vue 3.4 v-bind shorthand

packages/language-service/src/injectTypes.ts, packages/language-service/src/virtual-code.ts, packages/playground/src/pages/about.vine.ts
=> fix(lang-service): add missing component common props

packages/compiler/src/analyze.ts, packages/compiler/src/transform.ts, packages/compiler/src/types.ts, packages/compiler/tests/__snapshots__/analyze.spec.ts.snap, packages/language-service/src/virtual-code.ts, packages/playground/src/components/fixtures.vine.ts, pnpm-lock.yaml, pnpm-workspace.yaml
=> fix(lang-service): add missing expose props

package.json, packages/compiler/src/template/walk.ts, packages/playground/src/components/fixtures.vine.ts, packages/vscode-ext/package.json
Thanks for @Soya-xy 
Mini-reproduction in https://github.com/Soya-xy/mini-vine-repo , using extension v0.3.12
=> fix(lang-service): missing used-in-template binding records for volar

packages/language-server/src/plugins/vine-template.ts, packages/language-service/src/virtual-code.ts, packages/playground/src/components/fixtures.vine.ts
=> fix(lang-service): completions for auto-import components in global

packages/language-service/src/virtual-code.ts
=> fix(lang-service): should shallow unref VLS context object

packages/language-service/src/injectTypes.ts, packages/language-service/src/virtual-code.ts, packages/playground/src/pages/about.vine.ts
Fixing incorrect inferred type by `useTemplateRef`.
=> fix(lang-service): useTemplateRef declaration type incorrect

package.json, packages/compiler/src/validate.ts, packages/compiler/tests/validate.spec.ts
=> fix(compiler): allow vineExpose anything in compile time

packages/compiler/src/babel-helpers/ast.ts, packages/compiler/src/index.ts, packages/compiler/src/transform.ts, packages/compiler/src/types.ts, packages/compiler/tests/__snapshots__/transform.spec.ts.snap, packages/compiler/tests/transform.spec.ts, packages/playground/src/pages/about.vine.ts
=> fix(compiler): should aware of local ExportNamedDeclaration

packages/language-server/src/plugins/vine-template.ts
=> fix(lang-service): emit events completion items should be updated

packages/create-vue-vine/src/flags/index.ts, packages/create-vue-vine/src/utils/clack.ts, packages/create-vue-vine/template/code/css/unocss/package.json, packages/create-vue-vine/template/code/css/unocss/src/styles/index.ts, packages/create-vue-vine/template/code/css/unocss/uno.config.ts, packages/create-vue-vine/template/code/css/unocss/vite.config.ts, packages/docs/src/introduction/ecosystem.md, packages/docs/src/zh/introduction/ecosystem.md
=> feat(create-vue-vine): support unocss

packages/language-server/src/plugins/vine-template.ts
We should only update for current file.
=> fix: correction for #243

packages/create-vue-vine/src/flags/index.ts, packages/docs/src/introduction/ecosystem.md, packages/docs/src/zh/introduction/ecosystem.md
=> chore: unocss typo

packages/language-service/src/injectTypes.ts, packages/language-service/src/shared.ts, packages/language-service/src/virtual-code.ts
=> fix(language-service): fix the generated vine function type

packages/create-vue-vine/package.json, packages/create-vue-vine/template/code/css/tailwind/package.json, packages/create-vue-vine/template/code/css/tailwind/postcss.config.js, packages/create-vue-vine/template/code/css/tailwind/src/styles/tailwind.css, packages/create-vue-vine/template/code/css/tailwind/vite.config.ts, packages/create-vue-vine/template/common/src/styles/main.css, packages/create-vue-vine/template/common/vite.config.ts, packages/playground/uno.config.ts, pnpm-lock.yaml, pnpm-workspace.yaml
Refer to https://tailwindcss.com/blog/tailwindcss-v4
=> feat(cli): switch to tailwind 4 configs

packages/compiler/src/analyze.ts, packages/compiler/src/babel-helpers/ast.ts, packages/compiler/src/style/create-import-statement.ts, packages/compiler/src/types.ts, packages/compiler/tests/__snapshots__/transform.spec.ts.snap, packages/compiler/tests/analyze.spec.ts, packages/e2e-test/src/external-style-import.vine.ts, packages/e2e-test/src/router.ts, packages/e2e-test/src/styles/e2e.css, packages/e2e-test/tests/basic.spec.ts, packages/language-service/src/shared.ts, packages/language-service/src/virtual-code.ts, packages/language-service/tests/__snapshots__/virtual-code.spec.ts.snap, packages/playground/vite.config.ts, packages/vite-plugin/src/index.ts
1. External style import incorrect and add e2e test case
2. Support navigation
=> fix(vite-plugin): import external style

packages/vite-plugin/src/index.ts
Why deleted `enforce: "pre"`?
Because we handled the files id resolving, virtual module loading and transforming before all Vite built-in plugins, but it's a crucial for file paths to be load normally by `"vite:resolve"` plugin or we'll encounter problems like #257 fixed, that PR was a temporary solution but here is the key.
=> refactor(vite-plugin): migrate to not enforce: pre

packages/language-service/tests/__snapshots__/virtual-code.spec.ts.snap
=> test: update snapshot

packages/compiler/src/analyze.ts, packages/compiler/src/types.ts, packages/docs/src/specification/props.md, packages/docs/src/zh/specification/props.md, packages/e2e-test/src/app.vine.ts, packages/e2e-test/src/props-destructure.vine.ts, packages/e2e-test/src/router.ts, packages/e2e-test/tests/basic.spec.ts, packages/language-server/src/pipeline/get-component-props.ts, packages/language-server/src/pipeline/get-element-attrs.ts, packages/language-server/src/pipeline/shared.ts, packages/language-server/src/plugins/vine-template.ts, packages/language-server/src/types.ts, packages/language-service/src/injectTypes.ts, packages/playground/src/pages/about.vine.ts
- docs: update for destructure props code transpiled result description
- e2e: add test case for props destructure
- lang-service: fix props completion lost in propsDefinitionBy = typeReference
=> enhance: many updates as one commit

packages/compiler/src/analyze.ts, packages/compiler/src/babel-helpers/ast.ts, packages/compiler/src/types.ts, packages/compiler/tests/__snapshots__/analyze.spec.ts.snap, packages/e2e-test/src/fixtures/key-cases.vine.ts, packages/e2e-test/src/fixtures/vine-prop.vine.ts, packages/e2e-test/tests/basic.spec.ts, packages/language-service/src/virtual-code.ts, packages/language-service/tests/__snapshots__/virtual-code.spec.ts.snap, pnpm-lock.yaml
=> feat(lang-service): support JSDoc for vineProp declaration

packages/e2e-test/package.json, packages/eslint-plugin/src/rules/format/format-prefer-template.ts, packages/language-service/src/virtual-code.ts, packages/language-service/tests/__snapshots__/virtual-code.spec.ts.snap, pnpm-lock.yaml
- fix a typing regression in JSX compat
- allow users to give an option to turn off `format-prefer-template` in template.
=> fix(lang-service): regression in JSX compat

packages/e2e-test/src/app.vine.ts, packages/e2e-test/src/fixtures/vine-emits.vine.ts, packages/e2e-test/src/router.ts, packages/e2e-test/tests/basic.spec.ts, packages/language-server/package.json, packages/language-server/src/index.ts, packages/language-server/src/plugins/vine-css-service.ts, packages/language-server/src/plugins/vine-template.ts, packages/language-service/typescript-plugin/types.ts, packages/language-service/typescript-plugin/utils.ts, pnpm-lock.yaml, pnpm-workspace.yaml
Avoid incorrect caching for props/events completions list
=> fix(lang-service): gurantee using pipeline for completions list

packages/compiler/src/template/compose.ts, packages/compiler/src/types.ts, packages/e2e-test/src/app.vine.ts, packages/e2e-test/src/fixtures/boolean-cast.vine.ts, packages/e2e-test/src/router.ts, packages/e2e-test/tests/basic.spec.ts, packages/language-service/src/vine-ctx.ts, packages/language-service/src/virtual-code.ts
- Close #296 
- Fix regression of HTML Emmet feature lost
=> refactor(compiler): make transform bare bool optional

packages/eslint-parser/src/index.ts, packages/eslint-plugin/src/rules/format/format-vine-template.ts, packages/eslint-plugin/src/utils.ts, packages/eslint-plugin/tests/autofix.spec.ts
Improve template formatting to ensure align with Prettier output result and add base indent.
=> fix(eslint): improve formatting when meet HTML comments
