vue-vine/vue-vine

packages/compiler/index.ts
Re-defining the same options in [parse.ts#L5](https://github.com/sakanjo/vue-vine/blob/c874b3233bc3feca4fef91545fd9f7988a567562/packages/compiler/src/babel-helpers/parse.ts#L5).
=> refactor: remove duplicate options

packages/compiler/src/validate.ts
In the loop of validating all the Vine component functions, if the first one has errors but the following one doesn't, the final validating result is incorrect.
=> fix(validateVine): Error detection

packages/compiler/src/analyze.ts, packages/compiler/src/babel-helpers/ast.ts, packages/compiler/src/constants.ts, packages/compiler/src/template/compose.ts, packages/compiler/src/transform.ts, packages/compiler/src/types.ts, packages/compiler/src/validate.ts, packages/compiler/tests/__snapshots__/transform.spec.ts.snap, packages/compiler/tests/analyze.spec.ts, packages/compiler/tests/transform.spec.ts, packages/compiler/tests/validate.spec.ts, packages/playground/package.json, packages/playground/src/vine/app.vine.ts, packages/vue-vine/types/macros.d.ts, pnpm-lock.yaml
Same usage as Vue.js official `defineModel`.
https://vuejs.org/api/sfc-script-setup.html#definemodel
=> feat(compiler): implement vineModel

package.json
As the [pnpm docs](https://pnpm.io/cli/run#--stream) says, stream build will follow topological sorting, and build parallelly by sub-processes. This will save a **LOT** of time on build execution time.
=> chore: speed up build process

.vscode/settings.json
For some contributors that didn't config eslint stylistic on their global settings, this is required for a better DX.
=> chore: explicitly config the ESLint extension settings

packages/playground/src/pages/about.vine.ts, packages/playground/src/pages/home.vine.ts, packages/vite-plugin/src/index.ts
Vite won't transpile ts code if we override esbuild config to exclude `/*,vine.ts$/`.
We can process before esbuild.
=> fix(vite): esbuild should be processed after vue-vine

scripts/run-test.js
The test will fail in CI, but will never throw, which means CI never run test in `eslint-parser`
=> fix: test script

packages/compiler/src/babel-helpers/ast.ts, packages/compiler/tests/ast.spec.ts, packages/compiler/tests/transform.spec.ts, packages/vscode-ext/package.json
Fix: #100 
Make VSCode extension only activate on `*.vine.ts` files.
=> fix(compiler): parse simple component definition

packages/playground/src/pages/home.vine.ts, packages/vscode-ext/package.json, packages/vscode-ext/snippets/vine-snippets.code-snippets
* `vcf`: means `v(ine) c(omponent) f(unction)`
For quick inserting a component function
https://github.com/user-attachments/assets/5b0a875a-4cbb-4c3a-8fa0-e065669330ca
* `vtpl`: means `v(ine) t(em)pl(ate)`
For quick inserting a vine\`...\` with a prettier-formated new line inside it
Preview image: 
https://github.com/user-attachments/assets/7fd0787b-a36a-4dbf-a4ed-7976bc8ec84f
* `vsty`: means `v(ine) sty(le)`
For quick inserting a vineStyle(...)
Preview image: 
https://github.com/user-attachments/assets/427af17b-71e6-42d3-b64b-11d020eb796a
* `vstysc`: means `v(ine) sty(le) sc(oped)`
For quick inserting a vineStyle.scoped(...)
Preview image: 
https://github.com/user-attachments/assets/64d4dd5a-cf52-4fc1-b2f7-090c67804afe
* `vpr`: means `v(ine) pr(op)`
For quick inserting a `const …
=> feat(vscode-ext): add snippets

packages/docs/src/.vitepress/config.ts
I used `create-vue-vine` to create an initial project to experience vue vine online. (I wasn’t sure if such a template should be integrated into our monorepo or create a new repository in our organization, so I temporarily created it under my personal account. In the future, we can always move to it.)
I'll link this initial template to stackblitz so that users can experience vue vine online.
=> docs: add playground

packages/vite-plugin/package.json
Fixed an error that occurred when using `pnpm dev`.
src/vite/index.ts(3,8): error TS7016: Could not find a declaration file for module '@vue-vine/vite-plugin'. '/Users/tianteng/workspace/github/fork/vue-vine/packages/vite-plugin/dist/index.mjs' implicitly has an 'any' type.
MAIN     Try `npm i --save-dev @types/vue-vine__vite-plugin` if it exists or add a new declaration (.d.ts) file containing `declare module '@vue-vine/vite-plugin';`
=> fix(vite-plugin): Fixed prompt type missing in development mode

packages/compiler/src/analyze.ts, packages/compiler/src/babel-helpers/ast.ts, packages/compiler/src/constants.ts, packages/compiler/src/style/create-import-statement.ts, packages/compiler/src/style/order.ts, packages/compiler/src/types.ts, packages/compiler/tests/__snapshots__/transform.spec.ts.snap, packages/compiler/tests/transform.spec.ts, packages/language-service/src/index.ts, packages/playground/src/pages/home.vine.ts, packages/playground/src/styles/outside-example.css, packages/vite-plugin/src/constants.ts, packages/vite-plugin/src/hot-update.ts, packages/vite-plugin/src/index.ts, packages/vite-plugin/src/parse-query.ts, packages/vscode-ext/syntaxes/vine-inject.json, packages/vscode-ext/themes/rocking-vine.json, packages/vue-vine/types/macros.d.ts
<details>
<summary>中文说明</summary>
<br>
#154 的另一种解决方法
从一开始，我就只想重用 `vineStyle('../styles/test.css')` 来导入外部文件，但在为我们的 VSCode 扩展实现此功能时，我发现存在一些语法高亮问题。
```ts
vineStyle('... ...')
//              ^^^^ 我们已经设定这部分内容应该以 CSS/SCSS/Less/Stylus 语法来高亮
```
此外，在即将发布的 PR #152 中，我为我们自定义的 “Rocking Vine” VSCode 主题设计了新的样式（以便更美观地显示用户的 Vine 脚本文件视图）。我标记了一系列 TextMate 的范围选择器，以便以彩色突出显示特定的标记，但这些选择器是纯静态的，无法与 TS的语义环境集成。
```ts
// 测试样例：
vineStyle.import('../styles/test1.css')
vineStyle.import(`~/styles/test2.less`).scoped()```
```
对于未用作 “scoped” 的外部文件路径，我们可以将其直接转为一个导入语句。
```scss
import "path/to/external/file" as "external-file-alias"；
```
对于 “scoped” 的样式，情况稍微复杂一些。我们需要生成一个虚拟的文件导入语句，就像我们对于用户直接用 `vineStyle` 写样式内容所做的那样：
```ts
import '~/styles/test1.less?vineFileId=...&type=vine-style-external&scopeId=...&comp=...&lang=less&inde …
=> feat: support `vineStyle.import` for external style file

packages/create-vue-vine/src/utils/project.ts
=> fix(create-vue-vine): get correct template dir in `Windows`

packages/compiler/src/transform.ts, packages/compiler/tests/__snapshots__/transform.spec.ts.snap, packages/compiler/tests/transform.spec.ts
Close: #173 
- New unit test added: 
`packages/compiler/tests/transform.spec.ts` —— `'should transform top-level await expressions'`
=> fix(compiler): top-level await transform

packages/compiler/package.json, packages/compiler/src/analyze.ts, packages/compiler/src/index.ts, packages/compiler/src/ts-morph/create.ts, packages/compiler/src/ts-morph/resolve-props-type.ts, packages/compiler/src/types.ts, packages/compiler/src/validate.ts, packages/compiler/tests/__snapshots__/analyze.spec.ts.snap, packages/compiler/tests/analyze.spec.ts, packages/compiler/tests/test-utils.ts, packages/compiler/tests/transform.spec.ts, packages/compiler/tests/validate.spec.ts, packages/language-service/src/vine-ctx.ts, packages/language-service/src/virtual-code.ts, packages/playground/src/components/page-header.vine.ts, packages/playground/src/pages/test-ts-morph.vine.ts, packages/playground/src/router.ts, packages/playground/src/types.ts, packages/vite-plugin/package.json, packages/vite-plugin/src/index.ts, pnpm-lock.yaml
<image alt="types" src="https://github.com/user-attachments/assets/80a7bc90-a72d-42b9-bb83-51aad9fce913" width="400px" />
<image alt="component" src="https://github.com/user-attachments/assets/2947684d-8312-4641-95da-199e7992a58e" width="400px" />
As you can see, we can even leverage fields intellisense from external type.
It seems that compiling `.vine.ts` with ts-morph is still very fast
=> feat(compiler): use ts-morph to analyze external props type

packages/compiler/src/analyze.ts, packages/compiler/src/types.ts, packages/compiler/tests/analyze.spec.ts, packages/language-service/src/virtual-code.ts, packages/playground/src/pages/test-ts-morph.vine.ts
```ts
vineEmits(['foo', 'bar'])
```
`emits`'s definition like this should generate Volar virtual code as the following code:
```ts
emits: {
foo?: __VINE_VLS_MyComp_emits__["foo"]
bar?: __VINE_VLS_MyComp_emits__["bar"]
}
```
=> fix(compiler): emits defined by names should be optional

packages/compiler/src/index.ts, packages/compiler/src/style/order.ts, packages/compiler/src/transform.ts, packages/compiler/src/utils/topo-sort.ts, packages/docs/src/zh/specification/macros.md, packages/vite-plugin/src/hot-update.ts, packages/vscode-ext/CHANGELOG.md, packages/vscode-ext/package.json
Close #175 
When a non-Vine module (like #175 `.mdx` file) is hot-updated, it should trigger its importers' update.
If the importer is a `.vine.ts`, we should topo sort all components' name to analyze their dependency relationship, and get the last item to call `__VUE_HMR_RUNTIME.rerender()`, it means re-render all the related Vine components.
Thanks demo from @libondev  https://github.com/libondev/vue-vine-with-mdx
=> fix(vite-plugin): hot-updated module which are not `.vine.ts` should trigger Vine importer module updates

packages/compiler/src/analyze.ts, packages/compiler/src/types.ts, packages/compiler/tests/test-utils.ts, packages/language-service/src/vine-ctx.ts, packages/vscode-ext/tsup.config.ts
```
> vue-vine-extension@0.2.3 build /home/shenqingchuan/vue-vine/packages/vscode-ext
> NODE_ENV=production tsup
CLI Building entry: {"client":"./src/index.ts","server":"./node_modules/@vue-vine/language-server/bin/vue-vine-language-server.js"}
CLI Using tsconfig: tsconfig.json
CLI Building entry: {"index":"src/typescript-plugin.ts"}
CLI Using tsconfig: tsconfig.json
CLI tsup v8.3.5
CLI Using tsup config: /home/shenqingchuan/vue-vine/packages/vscode-ext/tsup.config.ts
CLI tsup v8.3.5
CLI Using tsup config: /home/shenqingchuan/vue-vine/packages/vscode-ext/tsup.config.ts
CLI Target: esnext
CLI Target: esnext
CJS Build start
CLI Cleaning output folder
CJS Build start
CJS node_modules/@vue-vine/typescript-plugin/index.js 10.70 MB
CJS ⚡️ Build success in 787ms
CJS dist/client.js 373.18 KB
CJS …
```
=> enhance(vsc-ext): decrease extension bundle size

packages/playground/package.json, packages/vue-vine/package.json, packages/vue-vine/src/index.ts, packages/vue-vine/src/utils/reactive.ts, packages/vue-vine/tsup.config.ts, pnpm-lock.yaml, pnpm-workspace.yaml
This first fixes the above problems. Secondly, I think that' vue-vine' is a dependency of dev, and it should not be mandatory to install' @vueuse/core' in the installed project. Therefore, I localized the functions I used, which has the advantage of reducing a direct dependency.
> 这首先修复了以上问题，其次我认为 `vue-vine` 作为dev 的依赖，不应该强制要求安装的项目中也同步安装 `@vueuse/core` 所以我将使用到的功能本地化了，这么做的好处是减少了一个直接依赖
=> fix(vue-vine): resolve `@vueuse/core` version abnormal

packages/language-service/src/injectTypes.ts, packages/language-service/src/virtual-code.ts
There're no type checking while passing props on `<slots />` element
Type check is working!
=> fix(lang-service): type check for passing props on slots element

packages/docs/src/specification/props.md
Propss -> Props
Not much, but honest work 🫡
=> fix: props page title has a typo

packages/compiler/src/transform.ts, packages/compiler/tests/__snapshots__/transform.spec.ts.snap, packages/compiler/tests/transform.spec.ts, packages/vite-plugin/src/hot-update.ts, packages/vite-plugin/src/index.ts
Currently, we're injecting some HMR helper code in compiler's transform phase, which is not correct, compiler should be a bundler-framework agnostic package.
`import.meta.hot` is only available in Vite, and we're planning to integrate with Rspack in the future.
=> fix(compiler): move hmr inject code to vite plugin

packages/language-service/src/injectTypes.ts, packages/playground/src/pages/about.vine.ts, packages/playground/vite.config.ts
Mentioned by @Soya-xy 
Some `any` type bindings that exported to template is omitted.
It's a mistake while fixing #171 , now we omit any in correct position.
=> fix(lang-service): conflicts with implicit any

packages/compiler/src/template/compose.ts, packages/compiler/src/transform.ts, packages/playground/vite.config.ts
in Vue compiler's generated render code, there will be something like the following example 
when you're using `unplugin-auto-import`, because you didn't write any import statement explicitly in source code.
```ts
const _component_PageHeader = _resolveComponent("PageHeader")
```
But before `unplugin-auto-import` (this is a Vite plugin) handles your code in Vite transform pipeline, the code must contain that identifier `PageHeader` as reference, so that it can be recognized.
so we transform this in Vine plugin phase:
```ts
const _component_PageHeader = (typeof PageHeader === 'undefined' ? _resolveComponent("PageHeader") : PageHeader);
```
=> fix(compiler): auto-import components're broken in prod mode

package.json, packages/language-server/package.json, packages/language-server/src/pipeline/get-component-props.ts, packages/language-server/src/pipeline/get-pipeline-server-port.ts, packages/language-server/src/plugins/vine-template.ts, packages/language-server/src/types.ts, packages/language-service/package.json, packages/language-service/src/index.ts, packages/language-service/src/injectTypes.ts, packages/language-service/src/virtual-code.ts, packages/language-service/typescript-plugin/index.ts, packages/language-service/typescript-plugin/pipeline.ts, packages/language-service/typescript-plugin/types.ts, packages/language-service/typescript-plugin/utils.ts, packages/language-service/typescript-plugin/visitors.ts, packages/playground/src/components/fixtures.vine.ts, packages/playground/src/pages/home.vine.ts, packages/vscode-ext/package.json, packages/vscode-ext/tsup.config.ts, pnpm-lock.yaml
Close #221 
We established a C/S architecture named "Pipeline server" on TS plugin initialization, (just like [vuejs/language-tools](https://github.com/vuejs/language-tools))
use the context of TS language service to communicate with VSCode extension.
=> feat(language-service): implement pipe server for component info

packages/language-service/typescript-plugin/index.ts, packages/language-service/typescript-plugin/proxy-ts-lang-service.ts
Why we need a proxy for TypeScript language service ??
Because we don't want to expose some variables that injected in virtual code by Volar, like `__createVineVLSCtx`, `__VINE_VLS_...`
and we also implement a proxy method for "Go to definition", like Vue language tools https://github.com/vuejs/language-tools/pull/5221, then users can drop extension [antfu's "Goto definitions"](https://github.com/antfu/vscode-goto-alias).
=> feat(lang-service): add ts lang service proxy

package.json, packages/compiler/src/analyze.ts, packages/compiler/src/template/compose.ts, packages/compiler/src/types.ts, packages/language-service/src/virtual-code.ts, packages/nuxt-module/playground/app.vue, packages/playground/src/components/debug.vine.ts, scripts/pre-commit.js
Now after you add a `ref="..."` on a HTML element or a component, you'll able to get intellisense when referencing it in params of `useTemplateRef( ... )`
=> feat(lang-service): intellisense and navigation for useTemplateRef

packages/compiler/src/analyze.ts, packages/compiler/src/ts-morph/resolve-props-type.ts, packages/compiler/src/utils/index.ts, packages/compiler/tests/ts-morph.spec.ts, packages/playground/src/pages/about.vine.ts, packages/playground/src/pages/home.vine.ts
Use ts-morph to resolve generic type parameters' constraint, check whether it is a boolean type
=> feat(compiler): analyze type generics in props literal

packages/compiler/src/analyze.ts, packages/language-service/src/virtual-code.ts
Fix VSCode extension broken:
`Error: ts-morph is not initialized.`
=> fix(compiler): disable component props resolving by ts-morph in ext

packages/compiler/src/analyze.ts, packages/compiler/src/babel-helpers/ast.ts, packages/compiler/src/types.ts, packages/compiler/tests/analyze.spec.ts, packages/language-service/src/virtual-code.ts
The current code generation process is completely sequential. However, the order in which users write vine macros within the function body is uncertain. Therefore, it is necessary to make each execution unit of the code generation correspond to the content of the source code.
=> fix(lang-service): virtual code generation should be sorted

packages/compiler/src/analyze.ts, packages/compiler/src/babel-helpers/ast.ts, packages/compiler/src/constants.ts, packages/compiler/src/index.ts, packages/compiler/src/style/order.ts, packages/compiler/src/transform.ts, packages/compiler/src/transform/steps.ts, packages/compiler/src/transform/utils.ts, packages/compiler/src/types.ts, packages/compiler/src/utils/index.ts, packages/compiler/src/utils/topo-sort.ts, packages/compiler/src/validate.ts, packages/compiler/tests/__snapshots__/transform.spec.ts.snap, packages/compiler/tests/transform.spec.ts, packages/playground/src/pages/about.vine.ts, packages/playground/src/pages/test-ts-morph.vine.ts, packages/vite-plugin/src/hot-update.ts, packages/vite-plugin/src/index.ts
The code in the transform phase of the existing code is extremely chaotic and has very poor readability, making maintenance extremely complicated. It is necessary to break it down into independent steps to facilitate the location of issues during troubleshooting
- HMR: renaming component function should give a reload instead of re-render only
=> refactor: transform code logic improving

.vscode/settings.json, packages/language-server/src/index.ts, packages/language-server/src/plugins/vine-folding-ranges.ts, packages/language-service/src/virtual-code.ts
=> fix(lang-service): folding .vine.ts for other part besides vine fn

packages/language-service/src/index.ts, packages/language-service/src/track.ts, packages/vscode-ext/src/index.ts, packages/vscode-ext/src/output-channel.ts, packages/vscode-ext/src/track.ts, packages/vscode-ext/src/view-features.ts
Now, this error notification will occur after restarting Vue Vine server
=> fix(lang-service): avoid error notification for output channel close

packages/docs/package.json, packages/docs/src/.vitepress/config.ts, packages/docs/src/specification/vibe.md, packages/docs/src/zh/specification/vibe.md, packages/e2e-test/utils/test-utils.ts, packages/vue-vine/src/defineVibe.ts, packages/vue-vine/tests/define-vibe.spec.ts, pnpm-lock.yaml, pnpm-workspace.yaml
You can destructure the data store returned by `initVibe`, because you may also want to access the data store in the provider component level.
```vue-vine
function App() {
const { productList } = initProductStore(/* ...*/)
// You can use the ref `productList` in the "relatively top-level" component.
return vine`...`
}
```
=> fix(vibe): allow get return value from initVibe

packages/compiler/src/babel-helpers/ast.ts, packages/compiler/src/constants.ts, packages/compiler/src/transform/steps.ts, packages/compiler/tests/__snapshots__/transform.spec.ts.snap, packages/compiler/tests/test-utils.ts, packages/compiler/tests/transform.spec.ts, packages/docs/src/specification/macros.md, packages/docs/src/zh/specification/macros.md, packages/e2e-test/src/app.vine.ts, packages/e2e-test/src/fixtures/custom-elements.vine.ts, packages/e2e-test/src/router.ts, packages/e2e-test/src/shims.d.ts, packages/e2e-test/src/styles/main.css, packages/e2e-test/tests/basic.spec.ts, packages/e2e-test/vite.config.ts, packages/language-service/src/virtual-code.ts, packages/language-service/tests/__snapshots__/virtual-code.spec.ts.snap, packages/language-service/tests/virtual-code.spec.ts, packages/vue-vine/types/macros.d.ts
=> fix(compiler): compilation for custom elements support

packages/e2e-test/src/fixtures/key-cases.vine.ts, packages/language-service/src/codegen.ts, packages/language-service/src/virtual-code.ts, packages/language-service/tests/__snapshots__/virtual-code.spec.ts.snap, packages/language-service/tests/utils.spec.ts
- Doesn't panic when linked code mappings not found (nullish value safety)
- Complicated event names should be wrapped in quotes to avoid syntax error in virtual code.
=> fix: complicated event names need quotes
